import org.junit.Test;
import utils.SmithWaterman;
import utils.entity.Pair;

import java.util.Arrays;
import java.util.List;

public class TestSW {
    @Test
    public void test1() {
        String seq1 = "GTGGCTGGTTCAGTTTACGTATTGCTGGCCATATCACATCTGGCCACCAGGAGCAGGGCCACTCCATTCCTGGAGCTTGAGATGAAGCTGCGGAAAGGCTTTGGGACAGTGGAGAGTGGGAAGGGAGAAATGCACCTCAACTGGGCTACCCCAGGTATCAGGCAGATAGCGGTGAGGAACAGAGCCTATGAGGAGGAGCAGGTTCAGGGCTTCTGCGGGCAGTACAGCTGATCTCCTCCATAGCACCTTCTCCAGGCCTGCCTGAGACTGAAACTTGCTCCTGTCCTCACCCACCGGAATTCCCCACCAATCCCCAATACCTTGGTCAGATAAGATATCCTCCTTGGTGTGATATTAGCATGCCATGCTGGCCAGTATACAGGCCTCATATTCTGTCTGTGAAGCTCCTATAAAACAGCTGCCAAAGGAGGTACCTCTCTCTTTGTCAGGTGAATCAACATAGAGGTTAGTGTATTATCAGGCAGATCTTCCAGATCTTGCACAGGAGGCAAATGATAAGGAGCTGCAGCTTTTTAATAGAAAAAAACAGATTTTTTAATTTGAAAGAAGCTACAGACTCTTTGACAGGAGCCCATAAATGTAAACAAGTGCTAAATACAGGTGGAAGGAGCCTTAAAATGCCTGAAAGCCAATTCTTCCCCTCTGTACAACAGACAGTAAATATTTAAGACCCATTAGAAAGCGGCAAATAGCTGATAGCCAATGGCTGCAGAAACCTTTAAACAATCAGCTTCCTCACACGTATTTACTTCCCTTGTTCAAATGCTGGTTATGTGTCATTATCATTTGTCTATATCCCTGGAGAACTATGCAAGAAATGAAAAAAATACAAAACTTCCTGAAAACTGAAAAATACAAATTCTCATATGTTGTATAATTAAAGTTAGCAAAAAACAGACATATACCTACTAGAACAGAAAAGAGCTGACTTCAAATATTGATTTACCACAGCAGTAATTACTTTATGTTTTCTGGCTTATTTTGAAACCTATTATTACTTTCACAGCAGCACACATCAACAGAACTGTCACCTAAGGGAGAAATAGAACTGGGCTGTAATTAATTTCTGGTGTCTCATCATGAAGCCTTTAATGTTGTGTAAAGGCTCTAACCCACTGAAAATCCCCCAACCTCTCCTCCCTCCCCTCTGTCCACAATACCCAAAATGTTTAATCGGTATCTCTGCAAGGAAACAGACTGCCTGAAGGAGAATGAGATGCAGTGGTATTTCTGCTAGTTGGTGTTAGTCCATTCCTTCCCTGACCGTGTGTGTCAAGAGAAGAATCAATCAAGTGGCCTCTCCTACTCCACTTTTTTTTTTTTTTTTTTCTGGGTTTGACTCCCATCTGCAACGAGAAAAACAGAAGGTGTACAATTCTTTGGAAGAATTTAACATGTAGATTCAGGCAATGGAGGAAATCATTACGCTTAACTGAGCCTATATTGTTAAAGGTTAAGTTTGGAGATTAAGAATGCCTCAGGAAAAGAAAATGGCTGATCTGAATAAAACCTTTCCATCAATTGGAAAACTACAACCACAGCAATGGAGATGAAGAAACTAAAGCAGATGTGACATTTGTGTTTCAGTACCTACGTTTACATTTTTTGAATTACTGTTCAAAGACCTTATAAGGCCTTTATAGGTCATGCAAAAGCAGTAGCCAGCGTCTAGATCTCATTTTACTCTCCTGTACGTGTGGTGAGCAATGCTTTAAGCACGATCTTGACTATGAAAAGAAAACAGGCCTACAGTACTTACGCGATATCTTATCTGACTCACAAGAATCAAATGTCAAAAGAGTTGTGTTGGGCAATAGGAAGTGCCAAGTTGGCTGACCTGGTCAAGGGTCAGGAGGTCACTTCTTGGAGAAGTGAAAATCAAGCTGAGGCCTGAAGAGGATGAGCAGTTGTGATGCAAGTAAAGAATGGGGTTAGTATTCTGAGCCAGAGGGAACAGCCAGAGTGCAGAGGAGGATGATGTGAATGAGGAACCTAACTGGTGTGACTAAGAGTGTACACAGCTGGCTTGGGTCAGCGGAGAAGAGGCTCTGAGACAGGCCAGGCCAGATCATGCAGGCCTTTGAGACCTGTGCCAAGAGGCGAACTGGATGCCTCAGGGCAGTAGGGAGCCAGCCCTGGGTGTTAAGTGAGTGTGGGTAGGGGGTAACATGCTTGGATCTGTTTTGGGGTGGATGACTCCAGCTGGAGAATGGGCTTGAAGGGTAGCTATAATCAAGCAGGGAGATGGGTTAGCTGGAGGACTATTGTGGTGGTATTTAGGCACTGATGGTAGCAACGTGGAAAGAGAGGTATGAATTCAAGATCTATGGAGGAGATATGTGGAGGATGAGAGGGAAAAAGGGCCGGGTGGCTCTGAGTTTTAGGCTTGCACGCCTGGGTGGAGAAAGTGGTGCCATCTTACTGAGATGGGCCACACTGGAGAAGGAGAAGCTGGTGCGGGTGAAAGTAGCAAGTCCAGTTTTGGCCACTCTAAGTCTGAAGGCATGACCACCATGTGGTGAGGACATCTCCAGTGCATGGGTGTGGAGCTGAGGTCTGGACCCCAGGGGAAGGCTCGGGCCCAGTGAGTCATTGGCTGGAGAGAATAAACAGGTGTATCATCAAGGTGGCCAGGCATGGTTACTCACTCCTGTAATCCAACGCTTTGGGAGGCCGAGGCAGGTGGGAAACCCGGGAGTTT";
        String seq2 = "ACGCGATATCTTATCTGACT";


        int[][] scoreMatrix = SmithWaterman.computeScoreMatrix(seq1, seq2);
//        SmithWaterman.printScoreMatrix(scoreMatrix);
//        int[] maxIndices = SmithWaterman.findMaxScoreIndices(scoreMatrix);
//        int maxScore = scoreMatrix[maxIndices[0]][maxIndices[1]];
//        String[] alignedSeqs = SmithWaterman.traceback(seq1, seq2, scoreMatrix, maxIndices);
//        String alignedSeq1 = alignedSeqs[0];
//        String alignedSeq2 = alignedSeqs[1];

//        System.out.println("maxIndices = " + maxIndices[0]+","+maxIndices[1]);
//        System.out.println("Alignment score: " + maxScore);
//        System.out.println("Aligned sequences:");
//        System.out.println(alignedSeq1);
//        System.out.println(alignedSeq2);

        int cuttoff = (int) (SmithWaterman.getMatchScore() * seq2.length() * 0.8);

        System.out.println("cuttoff = " + cuttoff);

        List<Pair> allLinker = SmithWaterman.findAllLinker(seq1, seq2, scoreMatrix, cuttoff);

//        System.out.println("allLinker = " + Arrays.toString(allLinker.toArray()));
    }

}
